// Auto-generated embedded catalog for Game of Thrones (TMDB 1399)
import 'google_sheets_catalog_service.dart';

class EmbeddedGotCatalog {
  static bool isAvailable(int tmdbId) => tmdbId == 1399;

  static SeriesCatalogData? getCatalog(int tmdbId) {
    if (tmdbId != 1399) return null;
    final rows = _rawGotRows;
    final seasonEps = <int, List<CatalogEpisode>>{};
    final seasonBatch = <int, List<CatalogBatchZip>>{};
    final allBatch = <CatalogBatchZip>[];

    for (final row in rows) {
      final type = row['type']?.toString() ?? '';
      final sNum = int.tryParse(row['season']?.toString() ?? '') ?? 1;
      if (type == 'batch_zip') {
        final bz = CatalogBatchZip.fromJson(row);
        seasonBatch.putIfAbsent(sNum, () => []).add(bz);
        allBatch.add(bz);
      } else if (type == 'episode') {
        final ep = CatalogEpisode.fromJson(row);
        seasonEps.putIfAbsent(sNum, () => []).add(ep);
      }
    }
    return SeriesCatalogData(
      tmdbId: 1399,
      title: 'Game of Thrones',
      seasonEpisodes: seasonEps,
      seasonBatchZips: seasonBatch,
      allBatchZips: allBatch,
    );
  }

  static const List<Map<String, dynamic>> _rawGotRows = [
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":8,"episode":"","quality":"480p","size":"1.4GB","vcloud_url":"https://nexdrive.fit/genxfm784776336312/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [1.4GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":8,"episode":"","quality":"720p","size":"3.8GB","vcloud_url":"https://nexdrive.fit/genxfm784776336320/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [3.8GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":8,"episode":"","quality":"1080p","size":"9GB","vcloud_url":"https://nexdrive.fit/genxfm784776336326/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [9GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":7,"episode":"","quality":"480p","size":"1.4GB","vcloud_url":"https://nexdrive.fit/genxfm784776336295/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [1.4GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":7,"episode":"","quality":"720p","size":"3.8GB","vcloud_url":"https://nexdrive.fit/genxfm784776336301/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [3.8GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":7,"episode":"","quality":"1080p","size":"9GB","vcloud_url":"https://nexdrive.fit/genxfm784776336306/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [9GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":6,"episode":"","quality":"480p","size":"1.8GB","vcloud_url":"https://nexdrive.fit/genxfm784776336274/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [1.8GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":6,"episode":"","quality":"720p","size":"5GB","vcloud_url":"https://nexdrive.fit/genxfm784776336278/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [5GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":6,"episode":"","quality":"1080p","size":"11.5GB","vcloud_url":"https://nexdrive.fit/genxfm784776336285/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [11.5GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":5,"episode":"","quality":"480p","size":"1.7GB","vcloud_url":"https://nexdrive.fit/genxfm784776336255/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [1.7GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":5,"episode":"","quality":"720p","size":"4.9GB","vcloud_url":"https://nexdrive.fit/genxfm784776336269/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [4.9GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":5,"episode":"","quality":"1080p","size":"12GB","vcloud_url":"https://nexdrive.fit/genxfm784776336261/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [12GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":4,"episode":"","quality":"480p","size":"1.9GB","vcloud_url":"https://nexdrive.fit/genxfm784776336231/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [1.9GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":4,"episode":"","quality":"720p","size":"5GB","vcloud_url":"https://nexdrive.fit/genxfm784776336239/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [5GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":4,"episode":"","quality":"1080p","size":"11.3GB","vcloud_url":"https://nexdrive.fit/genxfm784776336245/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [11.3GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":3,"episode":"","quality":"480p","size":"1.8GB","vcloud_url":"https://nexdrive.fit/genxfm784776336208/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [1.8GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":3,"episode":"","quality":"720p","size":"5GB","vcloud_url":"https://nexdrive.fit/genxfm784776336218/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [5GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":3,"episode":"","quality":"1080p","size":"11.5GB","vcloud_url":"https://nexdrive.fit/genxfm784776336223/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [11.5GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":3,"episode":"","quality":"2160p","size":"","vcloud_url":"https://nexdrive.fit/genxfm784776337600/","direct_stream_url":"","direct_download_url":"","label":"Download Now"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":2,"episode":"","quality":"480p","size":"1.6GB","vcloud_url":"https://nexdrive.fit/genxfm784776336171/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [1.6GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":2,"episode":"","quality":"720p","size":"5.4GB","vcloud_url":"https://nexdrive.fit/genxfm784776336181/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [5.4GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":2,"episode":"","quality":"1080p","size":"11.1GB","vcloud_url":"https://nexdrive.fit/genxfm784776336200/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [11.1GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":2,"episode":"","quality":"2160p","size":"","vcloud_url":"https://nexdrive.fit/genxfm784776337308/","direct_stream_url":"","direct_download_url":"","label":"Download Now"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":1,"episode":"","quality":"480p","size":"1.8GB","vcloud_url":"https://nexdrive.fit/genxfm784776336045/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [1.8GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":1,"episode":"","quality":"720p","size":"5GB","vcloud_url":"https://nexdrive.fit/genxfm784776336051/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [5GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":1,"episode":"","quality":"1080p","size":"11.5GB","vcloud_url":"https://nexdrive.fit/genxfm784776336060/","direct_stream_url":"","direct_download_url":"","label":"🧲 Batch/Zip [11.5GB]"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"batch_zip","season":1,"episode":"","quality":"2160p","size":"","vcloud_url":"https://nexdrive.fit/genxfm784776336678/","direct_stream_url":"","direct_download_url":"","label":"Download Now"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":1,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=PBk6POjU1JNWGUslwhc1eb4lg","url_480p":"https://fastdl.zip/embed?download=6h1Hd44YfaqpE1r6kW9k4vdyw","url_720p":"https://fastdl.zip/embed?download=PBk6POjU1JNWGUslwhc1eb4lg","url_1080p":"https://vcloud.fit/rsp5w_w98rd1s6c","label":"Episode 1"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":2,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=A1em3RXT0piR5JfHbM0nLtNvj","url_480p":"https://fastdl.zip/embed?download=Clb6jPOlMmd7cK0eYl1JgQFAk","url_720p":"https://fastdl.zip/embed?download=A1em3RXT0piR5JfHbM0nLtNvj","url_1080p":"https://vcloud.fit/8tdk1d2c1a5omr5","label":"Episode 2"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":3,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=upBUAUdpYcGO4G0fjlpCgnZpS","url_480p":"https://fastdl.zip/embed?download=XRm0U6MXktZC9InCGKYkDvt5O","url_720p":"https://fastdl.zip/embed?download=upBUAUdpYcGO4G0fjlpCgnZpS","url_1080p":"https://vcloud.fit/qc58jf1-f-p8jfm","label":"Episode 3"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":4,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=EY5iqEbDrUugDLSYO1a6dn2HD","url_480p":"https://fastdl.zip/embed?download=RCKgrPyq4krwqysLeFzPCoEGC","url_720p":"https://fastdl.zip/embed?download=EY5iqEbDrUugDLSYO1a6dn2HD","url_1080p":"https://vcloud.fit/g9k7gv0bk70g_di","label":"Episode 4"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":5,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=SOg96XdDeURLLnwumg7d4iRWz","url_480p":"https://fastdl.zip/embed?download=xgmGlh6AMTFKmVmeogTeBLP64","url_720p":"https://fastdl.zip/embed?download=SOg96XdDeURLLnwumg7d4iRWz","url_1080p":"https://vcloud.fit/isvdhiy4wpimdic","label":"Episode 5"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":6,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=oo8sLJwSyXRTUOECm8SA8rnRk","url_480p":"https://fastdl.zip/embed?download=Wh4OwlG0EghG5k4p2qcep5hc6","url_720p":"https://fastdl.zip/embed?download=oo8sLJwSyXRTUOECm8SA8rnRk","url_1080p":"https://vcloud.fit/npzypnl5y5p-5im","label":"Episode 6"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":7,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=aVxGhAuXcVBCcEIz3x31R0CTR","url_480p":"https://fastdl.zip/embed?download=Yu9RzZinmlmJEckuW60rR7IVd","url_720p":"https://fastdl.zip/embed?download=aVxGhAuXcVBCcEIz3x31R0CTR","url_1080p":"https://vcloud.fit/_ffbwkpxibytf-k","label":"Episode 7"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":8,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=5zipudJ2bSEAaAfyzh0PLlXEW","url_480p":"https://fastdl.zip/embed?download=gJTSTnoU76DVfV674JlYwNxUT","url_720p":"https://fastdl.zip/embed?download=5zipudJ2bSEAaAfyzh0PLlXEW","url_1080p":"https://vcloud.fit/55eoqkw3sn3kvol","label":"Episode 8"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":9,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=hITqNO72pZW04z8IW93eNazPX","url_480p":"https://fastdl.zip/embed?download=mfdBimSWCMKsB7hUONhDb6VKg","url_720p":"https://fastdl.zip/embed?download=hITqNO72pZW04z8IW93eNazPX","url_1080p":"https://vcloud.fit/qv2josj-j1hjom4","label":"Episode 9"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":1,"episode":10,"quality":"multi","size":"","vcloud_url":"https://fastdl.zip/embed?download=bMbYCZxgEYXxxId9UQeQqq30P","url_480p":"https://fastdl.zip/embed?download=zOS05uQ8efK6M955fstLUXLHq","url_720p":"https://fastdl.zip/embed?download=bMbYCZxgEYXxxId9UQeQqq30P","url_1080p":"https://vcloud.fit/oc76q8ab-2xaea6","label":"Episode 10"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":1,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/i0iibitylzcjf_v","url_480p":"https://vcloud.fit/oyxqdzojjof5y7f","url_720p":"https://vcloud.fit/i0iibitylzcjf_v","url_1080p":"https://vcloud.fit/qh6wi9uwqmkm_4v","label":"Episode 1"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":2,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/t-reqwurusmpt_w","url_480p":"https://vcloud.fit/pzdcjzpredhpxq1","url_720p":"https://vcloud.fit/t-reqwurusmpt_w","url_1080p":"https://vcloud.fit/unyazqdvuuzqvev","label":"Episode 2"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":3,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/xbz0boja027q--z","url_480p":"https://vcloud.fit/zkhtctstfzhjzch","url_720p":"https://vcloud.fit/xbz0boja027q--z","url_1080p":"https://vcloud.fit/otiz_vqf_w_o1k3","label":"Episode 3"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":4,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/dvov_yteesopoeq","url_480p":"https://vcloud.fit/aymkdcwwdftwhtw","url_720p":"https://vcloud.fit/dvov_yteesopoeq","url_1080p":"https://vcloud.fit/4d2ka4x4yiztx3z","label":"Episode 4"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":5,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/ye0dc6csyejjrsd","url_480p":"https://vcloud.fit/gaeqsqq6ktfjjfl","url_720p":"https://vcloud.fit/ye0dc6csyejjrsd","url_1080p":"https://vcloud.fit/qp4q4piiaq1d4dq","label":"Episode 5"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":6,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/9dgl-bfvofzr7lb","url_480p":"https://vcloud.fit/kkfkcm6envejs6w","url_720p":"https://vcloud.fit/9dgl-bfvofzr7lb","url_1080p":"https://vcloud.fit/r12ddogirjg1u1d","label":"Episode 6"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":7,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/64nll9izlqwnqqz","url_480p":"https://vcloud.fit/mdzdqsf91fmfyyz","url_720p":"https://vcloud.fit/64nll9izlqwnqqz","url_1080p":"https://vcloud.fit/rnyusd2eprvddrb","label":"Episode 7"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":8,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/tpwmq-dbmepipw_","url_480p":"https://vcloud.fit/cig00sdwo0gfkgo","url_720p":"https://vcloud.fit/tpwmq-dbmepipw_","url_1080p":"https://vcloud.fit/b1lsbl1qwkc0muk","label":"Episode 8"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":9,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/epbzztpbrzqzs1p","url_480p":"https://vcloud.fit/hfjymyveu2n_mbq","url_720p":"https://vcloud.fit/epbzztpbrzqzs1p","url_1080p":"https://vcloud.fit/jiejij117embskr","label":"Episode 9"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":2,"episode":10,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/znqi-osp9ssn96i","url_480p":"https://vcloud.fit/haiwmh1wfhph7qp","url_720p":"https://vcloud.fit/znqi-osp9ssn96i","url_1080p":"https://vcloud.fit/lgfwtbjgbicebvc","label":"Episode 10"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":1,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/ppnt65bdq1jzyrb","url_480p":"https://vcloud.fit/vgkzj0y1vcfqhtq","url_720p":"https://vcloud.fit/ppnt65bdq1jzyrb","url_1080p":"https://vcloud.fit/wbamhjwmttfeh12","label":"Episode 1"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":2,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/d1b0bkrk0bhe4p9","url_480p":"https://vcloud.fit/c8xphdidqehlphf","url_720p":"https://vcloud.fit/d1b0bkrk0bhe4p9","url_1080p":"https://vcloud.fit/9cmzyoh1b2zpdhh","label":"Episode 2"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":3,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/ck8nrh1v_xvvcxh","url_480p":"https://vcloud.fit/1ttl1vtnntg-xqh","url_720p":"https://vcloud.fit/ck8nrh1v_xvvcxh","url_1080p":"https://vcloud.fit/il91ij9lj5k87n1","label":"Episode 3"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":4,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/2o0abwwiuhuqi1g","url_480p":"https://vcloud.fit/yyiilvgcc4b91vl","url_720p":"https://vcloud.fit/2o0abwwiuhuqi1g","url_1080p":"https://vcloud.fit/hma0hjtl70na1hj","label":"Episode 4"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":5,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/qov4bqnncyymybn","url_480p":"https://vcloud.fit/z49yahiebpziaxt","url_720p":"https://vcloud.fit/qov4bqnncyymybn","url_1080p":"https://vcloud.fit/fsfgmtdgdg3ddrd","label":"Episode 5"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":6,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/v1espceyt2p-5dg","url_480p":"https://vcloud.fit/ry5myqgrroiwqql","url_720p":"https://vcloud.fit/v1espceyt2p-5dg","url_1080p":"https://vcloud.fit/6flbll_jihvfz1r","label":"Episode 6"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":7,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/fcpp-bg7n4-hnwn","url_480p":"https://vcloud.fit/0jydn74o0-4a-1n","url_720p":"https://vcloud.fit/fcpp-bg7n4-hnwn","url_1080p":"https://vcloud.fit/b01l-jvl1610-y0","label":"Episode 7"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":8,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/eq1qoovecxhqhx4","url_480p":"https://vcloud.fit/a1phh_ruaxqq44q","url_720p":"https://vcloud.fit/eq1qoovecxhqhx4","url_1080p":"https://vcloud.fit/fywdxlmnzr0up15","label":"Episode 8"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":9,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/41mle9vmqg4vgaq","url_480p":"https://vcloud.fit/1enm0ynz0_x_att","url_720p":"https://vcloud.fit/41mle9vmqg4vgaq","url_1080p":"https://vcloud.fit/kpo1g233mojdpjp","label":"Episode 9"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":3,"episode":10,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/99w_v99wwdd4v2o","url_480p":"https://vcloud.fit/cwdl0sds1yxncku","url_720p":"https://vcloud.fit/99w_v99wwdd4v2o","url_1080p":"https://vcloud.fit/tvfwv1z7qot1otg","label":"Episode 10"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":1,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/xzggisexy0gb-gh","url_480p":"https://vcloud.fit/wcozuchvvw9vzpn","url_720p":"https://vcloud.fit/xzggisexy0gb-gh","url_1080p":"https://vcloud.fit/dcdu_ia-7kazuy7","label":"Episode 1"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":2,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/rjza9jcxbbhxx7x","url_480p":"https://vcloud.fit/5noo52ra5veukob","url_720p":"https://vcloud.fit/rjza9jcxbbhxx7x","url_1080p":"https://vcloud.fit/c1a2zawza-wb1zs","label":"Episode 2"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":3,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/d_2fdfvbgy7fn1r","url_480p":"https://vcloud.fit/0vseqjpsqscirxs","url_720p":"https://vcloud.fit/d_2fdfvbgy7fn1r","url_1080p":"https://vcloud.fit/1os2k-2mw-skglq","label":"Episode 3"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":4,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/ufn0ylb31w0j-ff","url_480p":"https://vcloud.fit/xbqguuubfqp79md","url_720p":"https://vcloud.fit/ufn0ylb31w0j-ff","url_1080p":"https://vcloud.fit/jzcz0y4b9cmyz0h","label":"Episode 4"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":5,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/y4tfxetqk-ffh66","url_480p":"https://vcloud.fit/svrkapz0asbkks1","url_720p":"https://vcloud.fit/y4tfxetqk-ffh66","url_1080p":"https://vcloud.fit/gm5mfpvv-7o7pyj","label":"Episode 5"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":6,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/ujs2ev1cgmps4_v","url_480p":"https://vcloud.fit/-h2z2y0ufzz_-9z","url_720p":"https://vcloud.fit/ujs2ev1cgmps4_v","url_1080p":"https://vcloud.fit/swb2uvb23o3dnnw","label":"Episode 6"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":7,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/fccljpec5ej1j_e","url_480p":"https://vcloud.fit/7v7114d1b1vetn8","url_720p":"https://vcloud.fit/fccljpec5ej1j_e","url_1080p":"https://vcloud.fit/lber1erxux1jxt1","label":"Episode 7"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":8,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/1m1zo1uxrr3u-ao","url_480p":"https://vcloud.fit/aaavjju01vqpqxq","url_720p":"https://vcloud.fit/1m1zo1uxrr3u-ao","url_1080p":"https://vcloud.fit/gj4htsolgs1hzgo","label":"Episode 8"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":9,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/sndncghx2n2ep_o","url_480p":"https://vcloud.fit/hqxhhrdrbmdm1lt","url_720p":"https://vcloud.fit/sndncghx2n2ep_o","url_1080p":"https://vcloud.fit/j_vjnupxnna3srn","label":"Episode 9"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":4,"episode":10,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/7nwekwseu73fxsn","url_480p":"https://vcloud.fit/p345dr_1o1z31v0","url_720p":"https://vcloud.fit/7nwekwseu73fxsn","url_1080p":"https://vcloud.fit/zat5o7ayj1k5yaz","label":"Episode 10"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":1,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/gs971m0sscppgxd","url_480p":"https://vcloud.fit/yjt_9xtjzz79jyt","url_720p":"https://vcloud.fit/gs971m0sscppgxd","url_1080p":"https://vcloud.fit/1g13j46jdddgs14","label":"Episode 1"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":2,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/iadnymlcaxsaytm","url_480p":"https://vcloud.fit/6af9afj5wsa32i5","url_720p":"https://vcloud.fit/iadnymlcaxsaytm","url_1080p":"https://vcloud.fit/mgyvbnnrbrkbmdl","label":"Episode 2"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":3,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/jlkcmiwwck9icuu","url_480p":"https://vcloud.fit/1xkh7lhkuhf3wpx","url_720p":"https://vcloud.fit/jlkcmiwwck9icuu","url_1080p":"https://vcloud.fit/ntrcibhq1r4sq80","label":"Episode 3"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":4,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/d1fi01tdwf7ckz0","url_480p":"https://vcloud.fit/wq2pkqyu2g2j19f","url_720p":"https://vcloud.fit/d1fi01tdwf7ckz0","url_1080p":"https://vcloud.fit/n51o59-ewo_m-b-","label":"Episode 4"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":5,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/f9zi9jkbnhjkxmj","url_480p":"https://vcloud.fit/dj26ghhwhyyyxhd","url_720p":"https://vcloud.fit/f9zi9jkbnhjkxmj","url_1080p":"https://vcloud.fit/cc5vcqvpvwfla1h","label":"Episode 5"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":6,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/eecbwpib2y12-hn","url_480p":"https://vcloud.fit/xcqwlpgfbd1vype","url_720p":"https://vcloud.fit/eecbwpib2y12-hn","url_1080p":"https://vcloud.fit/entgtpjsoyisvot","label":"Episode 6"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":7,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/0sar05tworjywgf","url_480p":"https://vcloud.fit/ziaoooccnijvczc","url_720p":"https://vcloud.fit/0sar05tworjywgf","url_1080p":"https://vcloud.fit/sssliiej1euojce","label":"Episode 7"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":8,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/-yng9rhsln1brhr","url_480p":"https://vcloud.fit/44et54t1iuci2ru","url_720p":"https://vcloud.fit/-yng9rhsln1brhr","url_1080p":"https://vcloud.fit/hxl-_f-oi-kh1i_","label":"Episode 8"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":9,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/0ppkne30lanlyar","url_480p":"https://vcloud.fit/tauiyztqr20zjft","url_720p":"https://vcloud.fit/0ppkne30lanlyar","url_1080p":"https://vcloud.fit/tntcetyzsn1qrva","label":"Episode 9"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":5,"episode":10,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/0inmrxcm_hq3coh","url_480p":"https://vcloud.fit/exxbibi8i-xwsib","url_720p":"https://vcloud.fit/0inmrxcm_hq3coh","url_1080p":"https://vcloud.fit/eg1e1ayiqfwilio","label":"Episode 10"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":1,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/j1gspj9mxcnhgnm","url_480p":"https://vcloud.fit/f1ufikkfbnrnoo0","url_720p":"https://vcloud.fit/j1gspj9mxcnhgnm","url_1080p":"https://vcloud.fit/odh1f1fvuvlf1ol","label":"Episode 1"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":2,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/mup9dukfal48uiz","url_480p":"https://vcloud.fit/ktna-7s5t0jkas0","url_720p":"https://vcloud.fit/mup9dukfal48uiz","url_1080p":"https://vcloud.fit/2i00lryi2qcvo0c","label":"Episode 2"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":3,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/zzqzqdyazsq2hnf","url_480p":"https://vcloud.fit/k0uuwrxqlk0bz0q","url_720p":"https://vcloud.fit/zzqzqdyazsq2hnf","url_1080p":"https://vcloud.fit/es_tiazfi1qku--","label":"Episode 3"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":4,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/kee6vxmiep3xzgu","url_480p":"https://vcloud.fit/jsc_j2zvt1wqay2","url_720p":"https://vcloud.fit/kee6vxmiep3xzgu","url_1080p":"https://vcloud.fit/vfo2roo2olv6e-f","label":"Episode 4"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":5,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/ahff1asgtiff1fg","url_480p":"https://vcloud.fit/4nmqvumdia-cdun","url_720p":"https://vcloud.fit/ahff1asgtiff1fg","url_1080p":"https://vcloud.fit/x7bm-mce1lhbcgi","label":"Episode 5"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":6,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/bt2y15veeqtq24e","url_480p":"https://vcloud.fit/ilwzdxwojihooly","url_720p":"https://vcloud.fit/bt2y15veeqtq24e","url_1080p":"https://vcloud.fit/iipldkvc-ppe5pa","label":"Episode 6"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":7,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/rsvrrdb1ebhdekr","url_480p":"https://vcloud.fit/cw3mvn-0h_l_jzm","url_720p":"https://vcloud.fit/rsvrrdb1ebhdekr","url_1080p":"https://vcloud.fit/otooujammvomauw","label":"Episode 7"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":8,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/jv7jq6j0u_p_day","url_480p":"https://vcloud.fit/eoxnelx1qqx-ppo","url_720p":"https://vcloud.fit/jv7jq6j0u_p_day","url_1080p":"https://vcloud.fit/gcogkvygrnynnvf","label":"Episode 8"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":9,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/plrqlnnxnxlrfhx","url_480p":"https://vcloud.fit/ruf552rkssgk225","url_720p":"https://vcloud.fit/plrqlnnxnxlrfhx","url_1080p":"https://vcloud.fit/ekf-ndikzhkof-s","label":"Episode 9"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":6,"episode":10,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/bkxnfwxgjf-yrw6","url_480p":"https://vcloud.fit/sqsccdsd-lc-ddj","url_720p":"https://vcloud.fit/bkxnfwxgjf-yrw6","url_1080p":"https://vcloud.fit/eiik1tel6ln6vni","label":"Episode 10"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":7,"episode":1,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/v19sv5yjsygsyp5","url_480p":"https://vcloud.fit/fa2kcwsp_i9i3qj","url_720p":"https://vcloud.fit/v19sv5yjsygsyp5","url_1080p":"https://vcloud.fit/wokjvwk1wdk1jhm","label":"Episode 1"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":7,"episode":2,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/htwtha7_7lqlhql","url_480p":"https://vcloud.fit/gp3agg1y55igg1a","url_720p":"https://vcloud.fit/htwtha7_7lqlhql","url_1080p":"https://vcloud.fit/nqpiq_0glinqcm0","label":"Episode 2"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":7,"episode":3,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/1g2sma7v2uxuuwt","url_480p":"https://vcloud.fit/o4y7gdweyxqyw0n","url_720p":"https://vcloud.fit/1g2sma7v2uxuuwt","url_1080p":"https://vcloud.fit/a_uym2fymau1b_f","label":"Episode 3"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":7,"episode":4,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/gxq1dkan61mc8c9","url_480p":"https://vcloud.fit/wvll3uy1jntqqny","url_720p":"https://vcloud.fit/gxq1dkan61mc8c9","url_1080p":"https://vcloud.fit/l0y6p0vp220nm41","label":"Episode 4"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":7,"episode":5,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/hlpaullkluc7aj2","url_480p":"https://vcloud.fit/an8lnak2aamur-7","url_720p":"https://vcloud.fit/hlpaullkluc7aj2","url_1080p":"https://vcloud.fit/jzh4ykjqf55c5my","label":"Episode 5"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":7,"episode":6,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/yetetlafc1lwcyy","url_480p":"https://vcloud.fit/sii715nu66jq3qs","url_720p":"https://vcloud.fit/yetetlafc1lwcyy","url_1080p":"https://vcloud.fit/y8f7xizwu9iwauc","label":"Episode 6"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":7,"episode":7,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/mrzstaserrzxfxt","url_480p":"https://vcloud.fit/scs71sclbsrt5yt","url_720p":"https://vcloud.fit/mrzstaserrzxfxt","url_1080p":"https://vcloud.fit/hlskvds1kgsdgev","label":"Episode 7"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":8,"episode":1,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/zwo5kbpl7rt_t5l","url_480p":"https://vcloud.fit/uvkiz9ngoghgu97","url_720p":"https://vcloud.fit/zwo5kbpl7rt_t5l","url_1080p":"https://vcloud.fit/mioupoup8usuikw","label":"Episode 1"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":8,"episode":2,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/-wwf2ljkmhbp-gz","url_480p":"https://vcloud.fit/d1hg6prhbffu5tb","url_720p":"https://vcloud.fit/-wwf2ljkmhbp-gz","url_1080p":"https://vcloud.fit/eqieuxiuqkjgfkx","label":"Episode 2"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":8,"episode":3,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/bm8sgw_asdemava","url_480p":"https://vcloud.fit/dz3i3i9p1vniiy1","url_720p":"https://vcloud.fit/bm8sgw_asdemava","url_1080p":"https://vcloud.fit/sjbpncbe6e_z2zm","label":"Episode 3"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":8,"episode":4,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/azr_amainakkazb","url_480p":"https://vcloud.fit/nswknw8w1jaita-","url_720p":"https://vcloud.fit/azr_amainakkazb","url_1080p":"https://vcloud.fit/m3vdwzmwa1w7zvw","label":"Episode 4"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":8,"episode":5,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/c-weiv1czxauv1i","url_480p":"https://vcloud.fit/c1_t28u_t3otev2","url_720p":"https://vcloud.fit/c-weiv1czxauv1i","url_1080p":"https://vcloud.fit/rb1xia5xd0h_jel","label":"Episode 5"},
    {"tmdb_id":1399,"title":"Game of Thrones","type":"episode","season":8,"episode":6,"quality":"multi","size":"","vcloud_url":"https://vcloud.fit/6ypdf781bp6bn1b","url_480p":"https://vcloud.fit/2itup-jwnnwh-oh","url_720p":"https://vcloud.fit/6ypdf781bp6bn1b","url_1080p":"https://vcloud.fit/sltih-vzlofwv-h","label":"Episode 6"},
  ];
}
